 
[[constraint]]
  name = "k8s.io/client-go"
  version = "v4.0.0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"

[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[override]]
  name = "github.com/spf13/cobra"
  revision = "d5bde60e022436203e377c47806e001418c16af3"