apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configuration.appname }}
  labels:
    app: {{ .Values.configuration.appname }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Values.configuration.name }}
type: Opaque
data:
  CLOUDABILITY_API_KEY: {{ .Values.secrets.CLOUDABILITY_API_KEY | b64enc | quote }}
