name: Metrics-Agent

on: [push]

jobs:
  snyk_scan:
    name: Snyk Scan
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@v2
      - name: Snyk Test
        run: snyk test  --severity-threshold=medium --org=cloudability
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk monitor
        run: snyk monitor --org=cloudability
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    name: Build
    needs: snyk_scan
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: Install tools
        run: make install-tools
      - name: Lint
        run: make lint
      - name: Run Tests
        run: make test

  test_e2e_amd:
    name: Test E2E AMD
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: run e2e AMD tests
        run: make test-e2e-all

  test_e2e_arm64:
    name: Test E2E ARM64
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: run e2e ARM64 tests
        run: make test-e2e-all PLATFORM=linux/arm64/v8 PLATFORM_TAG=arm64

  test_e2e_arm:
    name: Test E2E ARM
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: run e2e ARM64 tests
        run: make test-e2e-all PLATFORM=linux/arm/v7 PLATFORM=arm

  slackFinish:
    name: Notify Finish
    needs: [test_e2e_amd, test_e2e_arm64, test_e2e_arm]
    runs-on: ubuntu-18.04
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,action,eventName,ref,workflow
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

