name: Metrics-Agent

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - uses: actions/checkout@v2
      - name: Install tools
        run: |
          make install-tools
          GO111MODULE=on go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.1
      - name: Lint
        run: make lint
      - name: Run Tests
        run: make test

  test_e2e:
    name: Test E2E AMD
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - uses: actions/checkout@v2
      - name: run e2e AMD tests
        run: make test-e2e-all

